Version 0.1
Dhii/output-renderer-abstract pull request #2
Opened 2017-09-24 13:45 UTC by XedinUnknown

2017-10-05 08:43 UTC, mecha requested changes

2017-10-05 08:43 UTC, mecha commented on README.md
> +be used for other purposes. This is a good place to start of you are creating
Typo: _"This is a good place to start ~of~ if"_

2017-10-05 15:39 UTC, mecha approved these changes

2017-10-06 10:02 UTC, mecha reviewed
Just a quick rant on code cleanliness 😛

2017-10-06 10:02 UTC, mecha commented on test/unit/AbstractTemplateTest.php
> +        return $this->getMockForAbstractClass($paddingClassName);
I recommend that you return `$this->getMockBuilder($paddingClassName)` instead. See other comment.

2017-10-06 10:02 UTC, mecha commented on test/unit/AbstractTemplateTest.php
> +                ->will($this->returnValue(null));
There is no need to do this for every method. If you use a mock builder, you can do

```
$mockBuilder->setMethods(
    [
        'getValidationErrors',
        'getValidator',
        ...
    ]
)
```

and they will all be mocked to return `null` by default. In the end, you can then

```
return $mockBuilder->getMockForAbstractClass();
```

2017-10-19 09:17 UTC, mecha approved these changes
LGTM. If you're interested in some code cleanup duty, see my previous review. But it's otherwise unimportant.

2018-01-10 19:12 UTC, merged

2018-01-11 08:20 UTC, XedinUnknown commented
It appears there's more work to be done before initial release can happen. See #3.